// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iPassport.Infra.Contexts;

namespace iPassport.Infra.Migrations
{
    [DbContext(typeof(iPassportContext))]
    [Migration("20210504003542_Update_UserDetails_Remove_Colunm_PriorityGroup")]
    partial class Update_UserDetails_Remove_Colunm_PriorityGroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DiseaseVaccine", b =>
                {
                    b.Property<Guid>("DiseasesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaccinesId")
                        .HasColumnType("uuid");

                    b.HasKey("DiseasesId", "VaccinesId");

                    b.HasIndex("VaccinesId");

                    b.ToTable("DiseaseVaccine");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Auth2FactMobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Pin")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Auth2FactMobile");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Health", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Healths");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.HealthUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Ine")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsiblePersonName")
                        .HasColumnType("text");

                    b.Property<string>("ResponsiblePersonOccupation")
                        .HasColumnType("text");

                    b.Property<string>("ResponsiblePersonPhone")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UniqueCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj");

                    b.HasIndex("Ine")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.ToTable("HealthUnits");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.HealthUnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Identifyer")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("HealthUnitTypes");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.ImportedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ImportedFiles");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.ImportedFileDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErrorDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<Guid>("ImportedFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportedFileId");

                    b.ToTable("ImportedFileDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserDetailsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserDetailsId")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PassportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PassportId");

                    b.ToTable("PassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportUse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PassportDetailsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("PassportDetailsId");

                    b.ToTable("PassportUses");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorEnd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PriorityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PriorityGroups");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bond")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImportedFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PriorityGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("WasCovidInfected")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasTestPerformed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("ImportedFileId");

                    b.HasIndex("PlanId");

                    b.HasIndex("PriorityGroupId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDiseaseTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool?>("Result")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResultDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDiseaseTests");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserVaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Batch")
                        .HasColumnType("text");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Dose")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeCoren")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCpf")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("HealthUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitName")
                        .HasColumnType("text");

                    b.Property<int?>("UnityType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VaccineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HealthUnitId");

                    b.HasIndex("UserId");

                    b.HasIndex("VaccineId");

                    b.ToTable("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExpirationTimeInMonths")
                        .HasColumnType("integer");

                    b.Property<int>("ImmunizationTimeInDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxTimeNextDose")
                        .HasColumnType("integer");

                    b.Property<int>("MinTimeNextDose")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredDoses")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.VaccineManufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("VaccineManufacturers");
                });

            modelBuilder.Entity("DiseaseVaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.Vaccine", null)
                        .WithMany()
                        .HasForeignKey("VaccinesId")
                        .IsRequired();
                });

            modelBuilder.Entity("iPassport.Domain.Entities.HealthUnit", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.HealthUnitType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.ImportedFile", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "ImportingUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("ImportingUser");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.ImportedFileDetails", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.ImportedFile", "ImportedFile")
                        .WithMany("ImportedFileDetails")
                        .HasForeignKey("ImportedFileId")
                        .IsRequired();

                    b.Navigation("ImportedFile");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "UserDetails")
                        .WithOne("Passport")
                        .HasForeignKey("iPassport.Domain.Entities.Passport", "UserDetailsId")
                        .IsRequired();

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Passport", "Passport")
                        .WithMany("ListPassportDetails")
                        .HasForeignKey("PassportId")
                        .IsRequired();

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportUse", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.UserDetails", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.PassportDetails", "PassportDetails")
                        .WithMany("PassportUses")
                        .HasForeignKey("PassportDetailsId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Citizen");

                    b.Navigation("PassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.HealthUnit", "HealthUnit")
                        .WithMany()
                        .HasForeignKey("HealthUnitId");

                    b.HasOne("iPassport.Domain.Entities.ImportedFile", "ImportedFile")
                        .WithMany()
                        .HasForeignKey("ImportedFileId");

                    b.HasOne("iPassport.Domain.Entities.Plan", "Plan")
                        .WithMany("Users")
                        .HasForeignKey("PlanId");

                    b.HasOne("iPassport.Domain.Entities.PriorityGroup", "PriorityGroup")
                        .WithMany()
                        .HasForeignKey("PriorityGroupId");

                    b.Navigation("HealthUnit");

                    b.Navigation("ImportedFile");

                    b.Navigation("Plan");

                    b.Navigation("PriorityGroup");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDiseaseTest", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "User")
                        .WithMany("UserDiseaseTests")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserVaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.HealthUnit", "HealthUnit")
                        .WithMany("UserVaccines")
                        .HasForeignKey("HealthUnitId");

                    b.HasOne("iPassport.Domain.Entities.UserDetails", "UserDetails")
                        .WithMany("UserVaccines")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("UserVaccines")
                        .HasForeignKey("VaccineId")
                        .IsRequired();

                    b.Navigation("HealthUnit");

                    b.Navigation("UserDetails");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.VaccineManufacturer", "Manufacturer")
                        .WithMany("Vaccines")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.HealthUnit", b =>
                {
                    b.Navigation("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.ImportedFile", b =>
                {
                    b.Navigation("ImportedFileDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.Navigation("ListPassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.Navigation("PassportUses");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.Navigation("Passport");

                    b.Navigation("UserDiseaseTests");

                    b.Navigation("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.Navigation("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.VaccineManufacturer", b =>
                {
                    b.Navigation("Vaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
