// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iPassport.Infra.Contexts;

namespace iPassport.Infra.Migrations
{
    [DbContext(typeof(iPassportContext))]
    [Migration("20210227130006_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DiseaseVaccine", b =>
                {
                    b.Property<Guid>("DiseasesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaccinesId")
                        .HasColumnType("uuid");

                    b.HasKey("DiseasesId", "VaccinesId");

                    b.HasIndex("VaccinesId");

                    b.ToTable("DiseaseVaccine");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Auth2FactMobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Pin")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Auth2FactMobile");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Health", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Healths");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserDetailsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserDetailsId")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PassportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PassportId");

                    b.ToTable("PassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportUse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<Guid>("PassportDetailsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("PassportDetailsId");

                    b.ToTable("PassportUses");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Profile")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserVaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Dose")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VaccineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserDetailsId");

                    b.HasIndex("VaccineId");

                    b.ToTable("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExpirationTime")
                        .HasColumnType("integer");

                    b.Property<int>("ImunizationTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RequiredDoses")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.VaccineManufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("VaccineManufacturers");
                });

            modelBuilder.Entity("DiseaseVaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.Vaccine", null)
                        .WithMany()
                        .HasForeignKey("VaccinesId")
                        .IsRequired();
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "UserDetails")
                        .WithOne("Passport")
                        .HasForeignKey("iPassport.Domain.Entities.Passport", "UserDetailsId")
                        .IsRequired();

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Passport", "Passport")
                        .WithMany("ListPassportDetails")
                        .HasForeignKey("PassportId")
                        .IsRequired();

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportUse", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.UserDetails", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.PassportDetails", "PassportDetails")
                        .WithMany("PassportUses")
                        .HasForeignKey("PassportDetailsId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Citizen");

                    b.Navigation("PassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Plan", "Plan")
                        .WithMany("Users")
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserVaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "UserDetails")
                        .WithMany("UserVaccines")
                        .HasForeignKey("UserDetailsId");

                    b.HasOne("iPassport.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("UserVaccines")
                        .HasForeignKey("VaccineId")
                        .IsRequired();

                    b.Navigation("UserDetails");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.VaccineManufacturer", "Manufacturer")
                        .WithMany("Vaccines")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.Navigation("ListPassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.Navigation("PassportUses");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.Navigation("Passport");

                    b.Navigation("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.Navigation("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.VaccineManufacturer", b =>
                {
                    b.Navigation("Vaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
