// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iPassport.Infra.Contexts;

namespace iPassport.Infra.Migrations
{
    [DbContext(typeof(iPassportContext))]
    [Migration("20210226133946_Update_Auth2FactMobile")]
    partial class Update_Auth2FactMobile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiseaseVaccine", b =>
                {
                    b.Property<Guid>("DiseasesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VaccinesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiseasesId", "VaccinesId");

                    b.HasIndex("VaccinesId");

                    b.ToTable("DiseaseVaccine");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Auth2FactMobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Auth2FactMobile");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Health", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("Healths");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserDetailsId")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("PassportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PassportId");

                    b.ToTable("PassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportUse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("bit");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PassportDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("PassportDetailsId");

                    b.ToTable("PassportUses");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("DateTime");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternationalDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("DateTime");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportDoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserVaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<int>("Dose")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("VaccineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VaccineId");

                    b.ToTable("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<int>("ExpirationTime")
                        .HasColumnType("int");

                    b.Property<int>("ImunizationTime")
                        .HasColumnType("int");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("RequiredDoses")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.VaccineManufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("VaccineManufacturers");
                });

            modelBuilder.Entity("DiseaseVaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.Vaccine", null)
                        .WithMany()
                        .HasForeignKey("VaccinesId")
                        .IsRequired();
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "UserDetails")
                        .WithOne("Passport")
                        .HasForeignKey("iPassport.Domain.Entities.Passport", "UserDetailsId")
                        .IsRequired();

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Passport", "Passport")
                        .WithMany("ListPassportDetails")
                        .HasForeignKey("PassportId")
                        .IsRequired();

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportUse", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.UserDetails", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.PassportDetails", "PassportDetails")
                        .WithMany("PassportUses")
                        .HasForeignKey("PassportDetailsId")
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Citizen");

                    b.Navigation("PassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.Plan", "Plan")
                        .WithMany("Users")
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserVaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.UserDetails", "UserDetails")
                        .WithMany("UserVaccines")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.HasOne("iPassport.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("UserVaccines")
                        .HasForeignKey("VaccineId")
                        .IsRequired();

                    b.Navigation("UserDetails");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.HasOne("iPassport.Domain.Entities.VaccineManufacturer", "Manufacturer")
                        .WithMany("Vaccines")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Passport", b =>
                {
                    b.Navigation("ListPassportDetails");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.PassportDetails", b =>
                {
                    b.Navigation("PassportUses");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
                {
                    b.Navigation("Passport");

                    b.Navigation("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.Vaccine", b =>
                {
                    b.Navigation("UserVaccines");
                });

            modelBuilder.Entity("iPassport.Domain.Entities.VaccineManufacturer", b =>
                {
                    b.Navigation("Vaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
