// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iPassport.Infra.Contexts;

namespace iPassport.Infra.Migrations
{
    [DbContext(typeof(iPassportContext))]
    partial class iPassportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iPassport.Domain.Entities.Health", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("DateTime");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.Property<DateTime>("UpdateDate")
                    .HasColumnType("DateTime");

                b.HasKey("Id");

                b.ToTable("Healths");
            });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(300)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("UpdateDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Plans");
            });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Address")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("Birthday")
                    .HasColumnType("DateTime");

                b.Property<string>("BloodType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Breed")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CNS")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CPF")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("DateTime");

                b.Property<string>("FullName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Gender")
                    .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                b.Property<string>("Passport")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Photo")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("PlanId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("RG")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdateDate")
                    .HasColumnType("DateTime");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("PlanId");

                b.ToTable("UserDetails");
            });

            modelBuilder.Entity("iPassport.Domain.Entities.UserDetails", b =>
            {
                b.HasOne("iPassport.Domain.Entities.Plan", "Plan")
                    .WithMany("Users")
                    .HasForeignKey("PlanId");

                b.Navigation("Plan");
            });

            modelBuilder.Entity("iPassport.Domain.Entities.Plan", b =>
            {
                b.Navigation("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
