kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${APP_NAME}-${APP_GROUP}-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi