using System.ComponentModel.DataAnnotations;

namespace iPassport.Domain.Enums
{
    public enum EFileImportColumns
    {
        FullName = 0,
        Gender = 1,
        Birthday = 2,
        Cpf = 3,
        Cns = 4,
        Cnpj = 5,
        Occupation = 6,
        Bond = 7,
        PriorityGroup = 8,
        BloodType = 9,
        HumanRace = 10,
        CountryCode = 11,
        PhoneNumber = 12,
        Email = 13,
        Cep = 14,
        Address = 15,
        Number = 16,
        District = 17,
        City = 18,
        State = 19,
        Country = 20,
        WasCovidInfected = 21,
        WasTestPerformed = 22,
        TestDate = 23,
        Result = 24,
        ResultDate = 25,
        VaccineNameUniqueDose = 26,
        VaccineManufacturerNameUniqueDose = 27,
        BatchUniqueDose = 28,
        VaccinationDateUniqueDose = 29,
        EmployeeNameVaccinationUniqueDose = 30,
        EmployeeCpfVaccinationUniqueDose = 31,
        EmployeeCorenVaccinationUniqueDose = 32,
        HealthUnityCnpjUniqueDose = 33,
        HealthUnityIneUniqueDose = 34,
        HealthUnityCodeUniqueDose = 35,
        VaccineNameFirstDose = 36,
        VaccineManufacturerNameFirstDose = 37,
        BatchFirstDose = 38,
        VaccinationDateFirstDose = 39,
        EmployeeNameVaccinationFirstDose = 40,
        EmployeeCpfVaccinationFirstDose = 41,
        EmployeeCorenVaccinationFirstDose = 42,
        HealthUnityCnpjFirstDose = 43,
        HealthUnityIneFirstDose = 44,
        HealthUnityCodeFirstDose = 45,
        VaccineNameSecondDose = 46,
        VaccineManufacturerNameSecondDose = 47,
        BatchSecondDose = 48,
        VaccinationDateSecondDose = 49,
        EmployeeNameVaccinationSecondDose = 50,
        EmployeeCpfVaccinationSecondDose = 51,
        EmployeeCorenVaccinationSecondDose = 52,
        HealthUnityCnpjSecondDose = 53,
        HealthUnityIneSecondDose = 54,
        HealthUnityCodeSecondDose = 55,
        VaccineNameThirdDose = 56,
        VaccineManufacturerNameThirdDose = 57,
        BatchThirdDose = 58,
        VaccinationDateThirdDose = 59,
        EmployeeNameVaccinationThirdDose = 60,
        EmployeeCpfVaccinationThirdDose = 61,
        EmployeeCorenVaccinationThirdDose = 62,
        HealthUnityCnpjThirdDose = 63,
        HealthUnityIneThirdDose = 64,
        HealthUnityCodeThirdDose = 65
    }
}
