using System.ComponentModel.DataAnnotations;

namespace iPassport.Domain.Enums
{
    public enum EFileImportColumns
    {
        FullName = 0,
        Gender = 1,
        Birthday = 2,
        Cpf = 3,
        Cns = 4,
        Cnpj = 5,
        Occupation = 6,
        Bond = 7,
        PriorityGroup = 8,
        BloodType = 9,
        HumanRace = 10,
        CountryCode = 11,
        PhoneNumber = 12,
        Email = 13,
        Cep = 14,
        Address = 15,
        Number = 16,
        District = 17,
        City = 18,
        State = 19,
        Country = 20,
        WasCovidInfected = 21,
        WasTestPerformed = 22,
        TestDate = 23,
        Result = 24,
        ResultDate = 25,
        VaccineNameUniqueDose = 26,
        VaccineManufacturerNameUniqueDose = 27,
        BatchUniqueDose = 28,
        VaccinationDateUniqueDose = 29,
        EmployeeNameVaccinationUniqueDose = 30,
        EmployeeCpfVaccinationUniqueDose = 31,
        EmployeeCorenVaccinationUniqueDose = 32,
        HealthUnityCnpjUniqueDose = 33,
        HealthUnityIneUniqueDose = 34,
        VaccineNameFirstDose = 35,
        VaccineManufacturerNameFirstDose = 36,
        BatchFirstDose = 37,
        VaccinationDateFirstDose = 38,
        EmployeeNameVaccinationFirstDose = 39,
        EmployeeCpfVaccinationFirstDose = 40,
        EmployeeCorenVaccinationFirstDose = 41,
        HealthUnityCnpjFirstDose = 42,
        HealthUnityIneFirstDose = 43,
        VaccineNameSecondDose = 44,
        VaccineManufacturerNameSecondDose = 45,
        BatchSecondDose = 46,
        VaccinationDateSecondDose = 47,
        EmployeeNameVaccinationSecondDose = 48,
        EmployeeCpfVaccinationSecondDose = 49,
        EmployeeCorenVaccinationSecondDose = 50,
        HealthUnityCnpjSecondDose = 51,
        HealthUnityIneSecondDose = 52,
        VaccineNameThirdDose = 53,
        VaccineManufacturerNameThirdDose = 54,
        BatchThirdDose = 55,
        VaccinationDateThirdDose = 56,
        EmployeeNameVaccinationThirdDose = 57,
        EmployeeCpfVaccinationThirdDose = 58,
        EmployeeCorenVaccinationThirdDose = 59,
        HealthUnityCnpjThirdDose = 60,
        HealthUnityIneThirdDose = 61
    }
}
